#!/usr/bin/env python
# coding: utf-8

"""
Code to process a map_kmers file output of phgv2. 
Calculates genome coverage statistics:
1. Percentage of genome represented in the pangenome
2. Percentage of genome covered by the read mapping file

IMPORTANT: The BED file must be the one generated by the hvcf2bed function.
This ensures proper reference coordinate mapping (columns 7-10 are used).

Performed from output of phg version 2.4.4.158
Code developed at 31/04/2025

Uses as input:
- map_kmers file: output of phg map-kmers
- BED file: output of hvcf2bed (contains reference coordinates in columns 7-10)
"""


def ExtractGenomeFromBED(bed_file):
    """
    Extract genome name from BED file (column 6).
    BED format: ref_chr  ref_start  ref_end  -  ref_key  genome  chr  start  end  key
    """
    genome_names = set()
    
    with open(bed_file, 'r') as f:
        for line in f:
            if line.startswith("#") or line.strip() == "":
                continue
            fields = line.strip().split('\t')
            if len(fields) >= 6:
                genome_names.add(fields[5])  # Column 6 (0-indexed: 5)
    
    if len(genome_names) == 0:
        print("Error: No genomes found in BED file")
        return None
    
    if len(genome_names) > 1:
        print(f"Warning: Multiple genomes found in BED file: {genome_names}")
    
    genome = list(genome_names)[0]
    print(f"Query genome from BED file: {genome}")
    return genome


def LoadBEDToDataFrame(bed_file):
    """
    Load BED file directly into a pandas DataFrame, extracting reference coordinates.
    BED format: chr1  start  end  -  key1  genome  chr2  start2  end2  key2
    We extract: chr2 (col 7), start2 (col 8), end2 (col 9), key2 (col 10)
    """
    data_rows = []
    
    with open(bed_file, 'r') as f:
        for line in f:
            if line.startswith("#") or line.strip() == "":
                continue
            fields = line.strip().split("\t")
            if len(fields) < 10:  # Need at least 10 columns
                continue
            
            try:
                # Reference coordinates (columns 7, 8, 9, 10)
                ref_chr = fields[6]          # Column 7: reference chr
                ref_start = int(fields[7])   # Column 8: reference start
                ref_end = int(fields[8])     # Column 9: reference end
                ref_key = fields[9]          # Column 10: reference key
                
                data_rows.append({
                    'chr': ref_chr,
                    'start': ref_start,
                    'end': ref_end,
                    'key': ref_key
                })
            except (ValueError, IndexError):
                # Skip lines with invalid numeric values
                continue
    
    if not data_rows:
        raise ValueError(f"No valid data rows found in BED file: {bed_file}")
    
    df = pd.DataFrame(data_rows)
    return df


def FilterBEDByMapKmers(bed_df, map_kmers_file):
    """
    Filter BED DataFrame to only include keys found in map_kmers file.
    Returns a filtered DataFrame.
    """
    from tqdm import tqdm
    
    # Load map_kmers_file into memory as a set for fast lookups
    map_kmers_keys = set()
    with open(map_kmers_file, 'r') as f:
        for line in tqdm(f, desc="Loading map_kmers keys"):
            if line.startswith("#") or line.strip() == "" or line.startswith("HapIds"):
                continue
            fields = line.strip().split("\t")
            if len(fields) > 0:
                # Extract all keys (may be comma-separated)
                keys = fields[0].split(",")
                for key in keys:
                    map_kmers_keys.add(key.strip())
    
    # Filter the DataFrame to only include keys in map_kmers_keys
    filtered_df = bed_df[bed_df['key'].isin(map_kmers_keys)].copy()
    
    if filtered_df.empty:
        raise ValueError("No keys from BED file found in map_kmers file")
    
    return filtered_df


def CaptureChrFromBED (hapID_ranges_file_bed_query):
    """
    This function will capture the chromosome from the BED file, storing them in a list
    """
    chr_list = []
    with open (hapID_ranges_file_bed_query, 'r') as f:
        lines = f.readlines()
        lines = lines[1:]
        for line in lines:
            chr = line.split('\t')[0]
            if chr not in chr_list:
                chr_list.append(chr)
    chr_list.sort()
    #print(f"Chromosomes found in the BED file are: {chr_list}\n")
    return chr_list



def LoadGenomeLengths(fasta_file):
    """
    Load chromosome lengths from a FASTA file.
    
    Parameters:
    -----------
    fasta_file : str
        Path to the genome FASTA file
    
    Returns:
    --------
    dict : Dictionary with chromosome names as keys and lengths as values
    """
    chr_lengths = {}
    current_chr = None
    current_length = 0
    
    with open(fasta_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('>'):
                # Save previous chromosome
                if current_chr:
                    chr_lengths[current_chr] = current_length
                # Extract new chromosome name
                current_chr = line[1:].split()[0]  # Get first word after '>'
                current_length = 0
            else:
                # Add sequence length
                current_length += len(line)
        
        # Don't forget the last chromosome
        if current_chr:
            chr_lengths[current_chr] = current_length
    
    if not chr_lengths:
        raise ValueError(f"No sequences found in FASTA file: {fasta_file}")
    
    return chr_lengths



def CalculatePresentRanges(original_df, filtered_df):
    """
    Calculate and display the percentage of ranges present in filtered dataset.
    """
    original_count = len(original_df)
    filtered_count = len(filtered_df)
    
    if original_count == 0:
        raise Exception("Original BED DataFrame is empty")
    if filtered_count == 0:
        raise Exception("Filtered BED DataFrame is empty")
    
    if original_count == filtered_count:
        print(f"All the ranges are present in the filtered dataset")
    else:
        present_percentage = (filtered_count / original_count) * 100
        print(f"Present ranges: {filtered_count} / {original_count} ({present_percentage:.2f}%)")


def CalculateGenomeCoverage(bed_df, filtered_df, chr_lengths):
    """
    Calculate the percentage of the genome represented in the pangenome and covered by reads.
    
    Parameters:
    -----------
    bed_df : pandas.DataFrame
        Complete BED DataFrame with all reference coordinates (from hvcf2bed output)
    filtered_df : pandas.DataFrame
        Filtered DataFrame containing only keys found in map_kmers file
    chr_lengths : dict
        Dictionary with chromosome names and their actual lengths from FASTA
    
    Returns:
    --------
    dict : Dictionary containing coverage statistics
    """
    # Calculate total genome length from actual chromosome lengths
    total_genome_bp = sum(chr_lengths.values())
    
    pangenome_coverage = 0  # Total bases in pangenome (from BED file)
    read_coverage = 0       # Total bases covered by reads (from filtered DataFrame)
    
    # Group by chromosome and calculate coverage
    chr_list = sorted(bed_df['chr'].unique())
    coverage_by_chr = {}
    
    for chrom in sorted(chr_lengths.keys()):
        chr_actual_length = chr_lengths.get(chrom, 0)
        
        chr_bed = bed_df[bed_df['chr'] == chrom].sort_values('start') if chrom in bed_df['chr'].values else pd.DataFrame()
        chr_filtered = filtered_df[filtered_df['chr'] == chrom] if chrom in filtered_df['chr'].values else pd.DataFrame()
        
        # Calculate pangenome coverage (merge overlapping regions)
        if len(chr_bed) > 0:
            merged_ranges = []
            for _, row in chr_bed.iterrows():
                start = row['start']
                end = row['end']
                
                # Merge overlapping ranges
                if merged_ranges and start <= merged_ranges[-1][1]:
                    merged_ranges[-1] = (merged_ranges[-1][0], max(merged_ranges[-1][1], end))
                else:
                    merged_ranges.append((start, end))
            
            chr_pangenome_bp = sum(end - start for start, end in merged_ranges)
            pangenome_coverage += chr_pangenome_bp
        else:
            chr_pangenome_bp = 0
        
        # Calculate read coverage (merge overlapping regions)
        if len(chr_filtered) > 0:
            merged_ranges = []
            for _, row in chr_filtered.iterrows():
                start = row['start']
                end = row['end']
                
                # Merge overlapping ranges
                if merged_ranges and start <= merged_ranges[-1][1]:
                    merged_ranges[-1] = (merged_ranges[-1][0], max(merged_ranges[-1][1], end))
                else:
                    merged_ranges.append((start, end))
            
            chr_read_bp = sum(end - start for start, end in merged_ranges)
            read_coverage += chr_read_bp
        else:
            chr_read_bp = 0
        
        # Calculate percentages based on actual chromosome length
        pangenome_pct = (chr_pangenome_bp / chr_actual_length * 100) if chr_actual_length > 0 else 0
        read_pct = (chr_read_bp / chr_actual_length * 100) if chr_actual_length > 0 else 0
        
        coverage_by_chr[chrom] = {
            'actual_length': chr_actual_length,
            'pangenome_bp': chr_pangenome_bp,
            'read_bp': chr_read_bp,
            'pangenome_pct': pangenome_pct,
            'read_pct': read_pct
        }
    
    # Calculate total coverage percentages based on actual genome length
    pangenome_coverage_pct = (pangenome_coverage / total_genome_bp * 100) if total_genome_bp > 0 else 0
    read_coverage_pct = (read_coverage / total_genome_bp * 100) if total_genome_bp > 0 else 0
    
    # Prepare results
    results = {
        'total_genome_bp': total_genome_bp,
        'pangenome_bp': pangenome_coverage,
        'pangenome_coverage_pct': pangenome_coverage_pct,
        'read_covered_bp': read_coverage,
        'read_coverage_pct': read_coverage_pct,
        'by_chromosome': coverage_by_chr
    }
    
    return results


def DisplayGenomeCoverage(coverage_results, verbose=False):
    """
    Display genome coverage statistics in a formatted output.
    
    Parameters:
    -----------
    coverage_results : dict
        Dictionary returned from CalculateGenomeCoverage()
    verbose : bool
        If True, display per-chromosome statistics
    """
    print("\n" + "="*70)
    print("GENOME COVERAGE STATISTICS")
    print("="*70)
    print(f"Actual genome length (from FASTA): {coverage_results['total_genome_bp']:,} bp")
    print(f"Pangenome coverage: {coverage_results['pangenome_bp']:,} bp ({coverage_results['pangenome_coverage_pct']:.2f}%)")
    print(f"Read-mapped coverage: {coverage_results['read_covered_bp']:,} bp ({coverage_results['read_coverage_pct']:.2f}%)")
    print(f"Uncovered genome: {coverage_results['total_genome_bp'] - coverage_results['read_covered_bp']:,} bp ({100 - coverage_results['read_coverage_pct']:.2f}%)")
    print("="*70 + "\n")
    
    if verbose:
        print("Per-chromosome coverage:")
        print("-" * 100)
        print(f"{'Chr':>10s} | {'Actual Length':>15s} | {'Pangenome':>15s} | {'Pangenome %':>12s} | {'Read-mapped':>15s} | {'Read %':>10s}")
        print("-" * 100)
        for chrom, stats in sorted(coverage_results['by_chromosome'].items()):
            print(f"{chrom:>10s} | {stats['actual_length']:>15,} | {stats['pangenome_bp']:>15,} | {stats['pangenome_pct']:>11.2f}% | {stats['read_bp']:>15,} | {stats['read_pct']:>9.2f}%")
        print("-" * 100 + "\n")


import os
import gzip
import re
import subprocess
import argparse
import sys
from tqdm import tqdm
import pandas as pd


def main(args):
    """
    Main function to analyze genome coverage from pangenome and read mapping.
    
    Calculates:
    1. Percentage of genome represented in the pangenome (from BED file)
    2. Percentage of genome covered by read mapping (intersection with map_kmers keys)
    
    IMPORTANT: The BED file must be generated by the hvcf2bed function.
    This ensures reference coordinates are in columns 7-10.
    
    Returns coverage statistics for the entire genome and per-chromosome.
    """
    
    parser = argparse.ArgumentParser(
        prog="phgtools genome-intersection",
        description="Analyze genome intersection from map_kmers output and BED file with haplotype keys."
    )
    parser.add_argument("map_kmers_file", help="Path to the map_kmers output file")
    parser.add_argument("--bed-file", required=True, help="Path to the BED file generated by hvcf2bed (reference coordinates in columns 7-10)")
    parser.add_argument("--genome-fasta", required=True, help="Path to the reference genome FASTA file (used to get actual chromosome lengths)")
    parser.add_argument("-v", "--verbose", action="store_true", help="Enable verbose output")
    
    parsed_args = parser.parse_args(args)
    
    map_kmers_file = parsed_args.map_kmers_file
    bed_file = parsed_args.bed_file
    genome_fasta = parsed_args.genome_fasta
    verbose = parsed_args.verbose
    
    if verbose:
        print(f"Running the script with the following parameters:\n")
        print(f"Map kmers file: {map_kmers_file}\n")
        print(f"BED file: {bed_file}\n")
        print(f"Genome FASTA: {genome_fasta}\n")

    if not os.path.exists(map_kmers_file):
        print(f"File {map_kmers_file} does not exist")
        exit()
    if not os.path.exists(bed_file):
        print(f"File {bed_file} does not exist")
        exit()
    if not os.path.exists(genome_fasta):
        print(f"File {genome_fasta} does not exist")
        exit()

    # Load genome lengths from FASTA
    chr_lengths = LoadGenomeLengths(genome_fasta)
    if verbose:
        print(f"Loaded {len(chr_lengths)} chromosomes from FASTA file\n")
    
    # Extract genome name from BED file
    query_genome = ExtractGenomeFromBED(bed_file)
    
    # Load BED file directly into DataFrame (extracts reference coordinates)
    bed_df = LoadBEDToDataFrame(bed_file)
    if verbose:
        print(f"Loaded {len(bed_df)} regions from BED file\n")
    
    # Filter BED by map_kmers keys
    filtered_df = FilterBEDByMapKmers(bed_df, map_kmers_file)
    
    # Calculate and display coverage statistics
    CalculatePresentRanges(bed_df, filtered_df)
    
    # Calculate genome coverage using actual genome lengths
    coverage_results = CalculateGenomeCoverage(bed_df, filtered_df, chr_lengths)
    DisplayGenomeCoverage(coverage_results, verbose=verbose)


if __name__ == "__main__":
    import sys
    main(sys.argv[1:])

